### ISSUE TITLE
Add "allow-download" value to a "sandbox" attribute of iframe

### ISSUE THREAD

**Issue by sanederchik** [microsoft/PowerBI-visuals-tools#352]
Each custom visual made in Power BI is included in an `iframe` with a `allow-scripts` flag. Before the update, you could make a fancy interface of whatever you like and place a download button which worked well for loading images, documents and data in different formats. I have several custom visuals where this feature of downloading is really crucial in the company I work.

Now, according to `whatwg`, you need to put a `allow-download` flag into a `sandbox` of `iframe` to do it.
I kindly ask you to add it in the next release.

**Comment by sanederchik** [comment]
@arjunanag, please confirm that it is a crucial feature with your case

**Comment by sanederchik** [comment]
Any comments on this issue?
Today the tops of my company were very angry it's impossible to download a PDF versions of the custom visual I had created. I explained the reason why it happened, so they may be considering abandoning MS services in the future in favor of `Tableau`.

**Comment by arjunanag** [comment]
I found an alternative way to download files. User need to do "Alt+Click"
insted of click. It should work

**Comment by sanederchik** [comment]
I found out that a `custom visual` code, which is responsible for its rendering, is placed inside a `{host}/powerbi/libs/scripts/customVisualHost.bundle.js` file. Moreover, I discovered a special place where a `sandbox` attribute is used.

![image](https://user-images.githubusercontent.com/30187683/122382963-15458b80-cf73-11eb-9f0a-232970c220b4.png)

If it's not possible to change global `Power BI RS` settings policy, could you, please, help me with adding a `allow-downloads` value inside this `sandbox` attribute? Unfortunately, I couldn't find such a file at the `backend` side of a `PBIRS`.

**Comment by JoshMayberry** [comment]
Similarly, I would like to know how to add "allow-form' to the sandbox flags.
After well over a year of no activity on this issue though- I don't have much hope.

**Comment by zBritva** [comment]
@JoshMayberry Power BI visuals have [Download API](https://learn.microsoft.com/en-us/power-bi/developer/visuals/file-download-api). 

Why you need `allow-form`?

**Comment by sanederchik** [comment]
> @JoshMayberry Power BI visuals have [Download API](https://learn.microsoft.com/en-us/power-bi/developer/visuals/file-download-api).
> 
> Why you need `allow-form`?

It's good Microsoft has finally created methods to accomplish this issue. Not really convenient that limit of 10 MB was set but it's better than nothing.

Hence, I believe this issue ticket is solved and may be closed.

**Comment by sanederchik** [comment]
Partially solved by Download API

**Comment by JoshMayberry** [comment]
> @JoshMayberry Power BI visuals have [Download API](https://learn.microsoft.com/en-us/power-bi/developer/visuals/file-download-api).
> 
> Why you need `allow-form`?

There are two things I wanted to do that this bit me on.

1. Have a form in a custom visual that would submit a post request to an API.
2. Allow a silent authentication routine to happen that would use msal-node (Alternatively, if I could access cookies I could just use the existing login to check if the current user has permission to perform a specific action on our API. This would also allow our API to use sessions which it is not able to when the requests come from a sandboxed iframe).

**Comment by Tesax123** [comment]
Does anyone have a solution for this? It was still not added. I can't download a png from my plotly custom visual.

**Comment by zBritva** [comment]
@Tesax123 don't think it will be added in future, workaround is using [File Download API](https://learn.microsoft.com/en-us/power-bi/developer/visuals/file-download-api)

**Comment by zBritva** [comment]
@Tesax123 you need to inject JS code your visual to handle click on icon, in handler you need to take png and pass it to [File Download API](https://learn.microsoft.com/en-us/power-bi/developer/visuals/file-download-api)
